In [1]:
import tensorflow_probability as tfp
import numpy as np

In [2]:
p = [.2, .2, .2, .2, .2]
dist = tfp.distributions.Multinomial(total_count=1, probs=p)
for i in range(5):
    action = dist.sample(1)
    print("Action: ",action)

Instructions for updating:
back_prop=False is deprecated. Consider using tf.stop_gradient instead.
Instead of:
results = tf.while_loop(c, b, vars, back_prop=False)
Use:
results = tf.nest.map_structure(tf.stop_gradient, tf.while_loop(c, b, vars))
Action:  tf.Tensor([[1. 0. 0. 0. 0.]], shape=(1, 5), dtype=float32)
Action:  tf.Tensor([[0. 0. 0. 0. 1.]], shape=(1, 5), dtype=float32)
Action:  tf.Tensor([[0. 0. 0. 1. 0.]], shape=(1, 5), dtype=float32)
Action:  tf.Tensor([[1. 0. 0. 0. 0.]], shape=(1, 5), dtype=float32)
Action:  tf.Tensor([[1. 0. 0. 0. 0.]], shape=(1, 5), dtype=float32)


In [3]:
logits = [5,5, 5]
dist = tfp.distributions.Multinomial(total_count=1, logits=logits)
for i in range(5):
    action = dist.sample(1)
    print("Action: ",action)

Action:  tf.Tensor([[0. 1. 0.]], shape=(1, 3), dtype=float32)
Action:  tf.Tensor([[1. 0. 0.]], shape=(1, 3), dtype=float32)
Action:  tf.Tensor([[0. 1. 0.]], shape=(1, 3), dtype=float32)
Action:  tf.Tensor([[0. 0. 1.]], shape=(1, 3), dtype=float32)
Action:  tf.Tensor([[0. 1. 0.]], shape=(1, 3), dtype=float32)


In [5]:
test_action = dist.sample(1)
print(test_action)
print(np.where(test_action))
print(np.where(test_action)[0])
print(np.where(test_action)[-1])

tf.Tensor([[0. 1. 0.]], shape=(1, 3), dtype=float32)
(array([0], dtype=int64), array([1], dtype=int64))
[0]
[1]


In [20]:
arr1 = np.array([1,2])
print(arr1)
print(arr1.shape)
print(arr1.ndim)
arr1 = np.reshape(arr1,(1,2))
print(arr1)
print(arr1.shape)
print(arr1.ndim)

[1 2]
(2,)
1
[[1 2]]
(1, 2)
2
