In [1]:
d = {'key1': 1, 'key2': 2, 'key3': 3}

In [2]:
index_= dict((val, key) for key, val in d.items())

In [4]:
print(index_)

{1: 'key1', 2: 'key2', 3: 'key3'}


In [6]:
print(d.keys())

dict_keys(['key1', 'key2', 'key3'])


In [7]:
print(index_.keys())

dict_keys([1, 2, 3])


In [9]:
print(d.values())

dict_values([1, 2, 3])


In [10]:
print(index_.values())

dict_values(['key1', 'key2', 'key3'])


In [19]:
import numpy as np
import gym

In [16]:
np.inner((1,1,1),[1,2,3])+1

7

In [8]:
sum([0,0,1])

1

In [19]:
np.zeros(112)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
action_space = gym.spaces.Discrete(4)

In [23]:
print(action_space

Discrete(4)

In [51]:
state = 0
reward = 0
trajectory =[]

for i in range(3):
    for j in range(4):
        state = i+1
        reward = j+1
        trajectory.append((state,reward))
        

In [52]:
trajectory

[(1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (2, 1),
 (2, 2),
 (2, 3),
 (2, 4),
 (3, 1),
 (3, 2),
 (3, 3),
 (3, 4)]

In [15]:
trajectory[::-1]

[(3, 4),
 (3, 3),
 (3, 2),
 (3, 1),
 (2, 4),
 (2, 3),
 (2, 2),
 (2, 1),
 (1, 4),
 (1, 3),
 (1, 2),
 (1, 1)]

In [17]:
for idx,(state,reward) in enumerate(trajectory[::-1]):
    print(f"idx : {idx} , state : {state} , reward : {reward}")

idx : 0 , state : 3 , reward : 4
idx : 1 , state : 3 , reward : 3
idx : 2 , state : 3 , reward : 2
idx : 3 , state : 3 , reward : 1
idx : 4 , state : 2 , reward : 4
idx : 5 , state : 2 , reward : 3
idx : 6 , state : 2 , reward : 2
idx : 7 , state : 2 , reward : 1
idx : 8 , state : 1 , reward : 4
idx : 9 , state : 1 , reward : 3
idx : 10 , state : 1 , reward : 2
idx : 11 , state : 1 , reward : 1


In [24]:
np.array(trajectory[::-1])[:,0][1]

3

In [26]:
distinct_states = [str(i) for i in range(12)]

In [27]:
returns = {state: [] for state in distinct_states}

In [28]:
returns

{'0': [],
 '1': [],
 '2': [],
 '3': [],
 '4': [],
 '5': [],
 '6': [],
 '7': [],
 '8': [],
 '9': [],
 '10': [],
 '11': []}

In [29]:
grid_state_action_values = np.zeros((12, 4))
grid_state_action_values[3] = 1
grid_state_action_values[7] = -1

In [30]:
grid_state_action_values

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [-1., -1., -1., -1.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [32]:
possible_states = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11"]
possible_actions = ["0", "1", "2", "3"]
returns = {}
for state in possible_states:
    for action in possible_actions:
        returns[state + ", " + action] = []

In [33]:
returns

{'0, 0': [],
 '0, 1': [],
 '0, 2': [],
 '0, 3': [],
 '1, 0': [],
 '1, 1': [],
 '1, 2': [],
 '1, 3': [],
 '2, 0': [],
 '2, 1': [],
 '2, 2': [],
 '2, 3': [],
 '3, 0': [],
 '3, 1': [],
 '3, 2': [],
 '3, 3': [],
 '4, 0': [],
 '4, 1': [],
 '4, 2': [],
 '4, 3': [],
 '5, 0': [],
 '5, 1': [],
 '5, 2': [],
 '5, 3': [],
 '6, 0': [],
 '6, 1': [],
 '6, 2': [],
 '6, 3': [],
 '7, 0': [],
 '7, 1': [],
 '7, 2': [],
 '7, 3': [],
 '8, 0': [],
 '8, 1': [],
 '8, 2': [],
 '8, 3': [],
 '9, 0': [],
 '9, 1': [],
 '9, 2': [],
 '9, 3': [],
 '10, 0': [],
 '10, 1': [],
 '10, 2': [],
 '10, 3': [],
 '11, 0': [],
 '11, 1': [],
 '11, 2': [],
 '11, 3': []}

In [36]:
grid_state_action_values = np.zeros((12, 4))
grid_state_action_values

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
grid_state_action_values = np.zeros((4, 12))
grid_state_action_values

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [37]:
grid_state_action_values[2]

array([0., 0., 0., 0.])

In [50]:
action = np.random.choice(np.arange(4), p=(0.5,0.2,0.1,0.1))
action

ValueError: probabilities do not sum to 1

In [54]:
for step in reversed(trajectory):
    print(step)

(3, 4)
(3, 3)
(3, 2)
(3, 1)
(2, 4)
(2, 3)
(2, 2)
(2, 1)
(1, 4)
(1, 3)
(1, 2)
(1, 1)


In [55]:
trajectory

[(1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (2, 1),
 (2, 2),
 (2, 3),
 (2, 4),
 (3, 1),
 (3, 2),
 (3, 3),
 (3, 4)]